### PR TITLE
Proper fix for $digest, plus extra Grunt build

### PR DESCRIPTION
**Pull request by yakovkhalinsky**
This is the proper patch for the $digest issue fix in #2 .

I've also added a quick and dirty example (could possibly be expanded in the future).

I've also added a grunt build that minifies, and copies the updated library to the example.

Apologies again for the previously bad PR.

### CODE REVIEW

**Comment by theaqua** [comment]
I think grunt is overkill, you can install uglify-js and ESlint (not jshint) as devDeps and then make `npm scripts` for these tasks.

And thanks for maintaining!

**Comment by yakovkhalinsky** [comment]
True about grunt being overkill for just uglify and copy.

I am though planning to introduce some unit testing with karma and jasmine, which are easier to run via grunt.

What do you think?

**Comment by theaqua** [comment]
I don't think so.
https://github.com/karma-runner/karma-cli

It's easy and no external dependencies.

**Comment by theaqua** [comment]
I merge your PR because it's hotfix, but recommend remove grunt and use npm scripts. Thanks!

**Comment by yakovkhalinsky** [comment]
No worries :+1: I'll fix up the build tasks

**Pull request merged**
